# Generated by Django 5.0.2 on 2024-04-15 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PetProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namePet', models.CharField(max_length=200)),
                ('ownerprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lassie.ownerprofile')),
            ],
        ),
    ]
