# Generated by Django 5.0.2 on 2024-04-15 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DogBreed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('life_expectancy', models.CharField(max_length=50)),
                ('origin', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OwnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('adress', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('birthDate', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('notificaciones', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PetProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namePet', models.CharField(max_length=300)),
                ('Weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('age', models.IntegerField()),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medieum'), ('B', 'Big')], max_length=1)),
                ('files', models.FileField(upload_to='archivos/')),
                ('ownerprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lassie.ownerprofile')),
            ],
        ),
    ]
