# Generated by Django 5.0.2 on 2024-04-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lassie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petprofile',
            name='namePet',
            field=models.CharField(max_length=300),
        ),
    ]
