# Generated by Django 5.0.2 on 2024-04-15 23:18

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lassie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default=' ', max_length=128, region=None, unique=True),
        ),
    ]
