# Generated by Django 5.0.2 on 2024-04-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lassie', '0003_dogbreed_personality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogbreed',
            name='personality',
            field=models.JSONField(default=dict),
        ),
    ]
