# Generated by Django 5.0.2 on 2024-04-23 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lassie', '0004_alter_dogbreed_personality'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerprofile',
            name='notificaciones',
        ),
        migrations.RemoveField(
            model_name='ownerprofile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='ownerprofile',
            name='username',
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
