# Generated by Django 5.0.2 on 2024-04-23 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lassie', '0005_remove_ownerprofile_notificaciones_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownerprofile',
            old_name='adress',
            new_name='address',
        ),
    ]
