# Generated by Django 5.0.2 on 2024-04-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lassie', '0007_rename_weight_petprofile_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petprofile',
            name='petImage',
            field=models.ImageField(blank=True, null=True, upload_to='media/pet_images'),
        ),
    ]
