# Generated by Django 5.0.2 on 2024-04-29 22:08

import Lassie.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lassie', '0008_petprofile_petimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petprofile',
            name='medicalHistory',
            field=models.FileField(blank=True, null=True, upload_to=Lassie.models.rename_medical_history),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='petImage',
            field=models.ImageField(default='static/images/DOG_DEFAULT.jpg', upload_to=Lassie.models.rename_image),
        ),
    ]
