# Generated by Django 5.0.2 on 2024-04-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lassie', '0009_alter_petprofile_medicalhistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petprofile',
            name='age',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='medicalHistory',
            field=models.FileField(blank=True, null=True, upload_to='medical_histories'),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='petImage',
            field=models.ImageField(default='static/images/DOG_DEFAULT.png', upload_to='pet_images'),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('B', 'Big')], max_length=1),
        ),
    ]
