# Generated by Django 5.0.2 on 2024-04-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lassie', '0010_alter_petprofile_age_alter_petprofile_medicalhistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petprofile',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
    ]
