# Generated by Django 5.0.2 on 2024-05-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lassie', '0011_petprofile_allergies'),
    ]

    operations = [
        migrations.AddField(
            model_name='petprofile',
            name='petType',
            field=models.CharField(choices=[('D', 'Dog'), ('C', 'Cat'), ('O', 'Other')], default='D', max_length=1),
        ),
    ]
