# Generated by Django 5.0.2 on 2024-05-16 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lassie', '0012_petprofile_pettype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petprofile',
            name='breed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Lassie.dogbreed'),
        ),
    ]
