# Generated by Django 5.0.2 on 2024-05-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lassie', '0013_alter_petprofile_breed'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatBreed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('life_expectancy', models.CharField(max_length=50)),
                ('origin', models.CharField(max_length=100)),
                ('personality', models.JSONField(default=dict)),
            ],
        ),
    ]
