# Generated by Django 5.0.2 on 2024-05-16 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lassie', '0014_catbreed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catBreed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Lassie.catbreed')),
                ('dogBreed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Lassie.dogbreed')),
            ],
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='breed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Lassie.breed'),
        ),
    ]
