# Generated by Django 5.0.2 on 2024-05-19 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lassie', '0016_breed_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walks', models.CharField(max_length=2)),
                ('Food', models.CharField(max_length=2)),
                ('ownerprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lassie.ownerprofile')),
                ('petprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lassie.petprofile')),
            ],
        ),
    ]
