# Generated by Django 5.0.2 on 2024-05-20 23:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lassie', '0020_alter_dailytasks_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytasks',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 20, 23, 15, 24, 211294, tzinfo=datetime.timezone.utc)),
        ),
    ]
